## Add this to your configuration.yaml

modbus: !include modbus.yaml

midea_heatpump_hws:
  water_heatpump:
    heater_switch: switch.water_heatpump_on_off_toggle
    mode_sensor: sensor.water_heatpump_mode     
    temperature_sensor: sensor.water_heatpump_temperature_bottom_of_tank_T5L
    target_temperature: 65
    min_temp: 60
    max_temp: 65
    modbus_hub: waveshare1
    modbus_unit: 1
    target_temp_register: 2

climate:
  - platform: climate_template
    name: "Water Heat Pump Climate"
    unique_id: water_heatpump_climate
    modes: ["heat", "off"]
    current_temperature_template: "{{ states('sensor.water_heatpump_temperature_bottom_of_tank_T5L') }}"
    target_temperature_template: "{{ states('sensor.water_heatpump_target_temperature') }}"
    set_temperature:
      - service: modbus.write_register
        data:
          hub: waveshare1
          unit: 1
          address: 2
          value: "{{ temperature | int }}"
    set_hvac_mode:
      - service: "{{ 'switch.turn_on' if hvac_mode == 'heat' else 'switch.turn_off' }}"
        target:
          entity_id: switch.water_heatpump_on_off_toggle
    # min and max based off the user manual
    min_temp: 55
    max_temp: 70
    temp_step: 1
    precision: 1
