## Add this to your configuration.yaml

modbus: !include modbus.yaml

midea_heatpump_hws:
  water_heatpump:
    heater_switch: switch.water_heatpump_on_off_toggle
    mode_sensor: sensor.water_heatpump_mode     
    temperature_sensor: sensor.water_heatpump_temperature_bottom_of_tank_T5L
    target_temperature: 65
    min_temp: 60
    max_temp: 65
    modbus_hub: waveshare1
    modbus_unit: 1
    target_temp_register: 2